# Generated by Django 4.2.7 on 2024-02-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('title',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.category'),
        ),
    ]
