# Generated by Django 4.2.7 on 2024-02-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_category_alter_movies_options_movies_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('title',), 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
    ]
