# Generated by Django 4.2.7 on 2024-02-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movies_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='slug',
        ),
    ]
