# Generated by Django 4.2.7 on 2024-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_remove_movies_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default='demo', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
