# Generated by Django 4.2.7 on 2024-02-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_movies_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='slug',
        ),
    ]
