# Generated by Django 4.2.7 on 2024-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_remove_movies_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.TextField(),
        ),
    ]
