# Generated by Django 4.2.7 on 2024-02-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_alter_movies_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default='Null', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.category'),
        ),
    ]
