# Generated by Django 4.2.7 on 2024-02-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
